credentials:
  usernames:
    faisan:
      email: faisan
      name: FAISAN
      password: "$2b$12$SkANOZu/khoM782LDCvQ3.kK5OCGZoLlwP6yIlTWvzW/MCZprbkRG"
    utpl:
      email: utpl
      name: UTPL
      password: "$2b$12$PMcAXcacGzkg9Nb4zQih4.j1NFMQ5x8HWxN2DYDIdh4F6fJKEjSc."
cookie:
  expiry_days: 30
  key: "clave_secreta_aleatoria"
  name: "nombre_cookie_autenticacion"
preauthorized:
  emails:
    - aeulloa2@gmail.com
    - aeulloa3@gmail.com
