credentials:
  usernames:
    credifacil:
      email: credifacil
      name: CREDIFACIL
      password: "$2b$12$HZcffrqirWOr1L/HA7RkxOifAzlb3lXW1WOZILO6HLt2sM8XD6knK"
    utpl:
      email: utpl
      name: UTPL
      password: "$2b$12$x4pzZvBNEQNGVyG.Q2nn9evR9myC0e2aKicPpIMpSERnzccpqng7W"
cookie:
  expiry_days: 30
  key: "clave_secreta_aleatoria"
  name: "nombre_cookie_autenticacion"
preauthorized:
  emails:
    - aeulloa2@gmail.com
    - aeulloa3@gmail.com
