credentials:
  usernames:
    nando:
      email: nando
      name: NANDO
      password: "$2b$12$XzqfAV49IpijHPPOi7L41O9uvwsyA.zHTZtmEudhR8g.VNO8YZtu6"
    utpl:
      email: utpl
      name: UTPL
      password: "$2b$12$yA8nZfcxyMLmT6ctRLqMBes3OyWWnMJsO5rE4gEy3oIR8JGZHarjC"
cookie:
  expiry_days: 30
  key: "clave_secreta_aleatoria"
  name: "nombre_cookie_autenticacion"
preauthorized:
  emails:
    - aeulloa2@gmail.com
    - aeulloa3@gmail.com
